recipe: default.v1


language: en


pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CountVectorsFeaturizer"
  alias: "cvf-word"
- name: "DIETClassifier"
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  featurizers: ["cvf-word"]
  epochs: 100



policies:

  - name: MemoizationPolicy
    max_history: 3
    priority: 3
  - name: TEDPolicy
    max_history: 3
    epochs: 200
  - name: RulePolicy
  
